### PR TITLE
Add Pest v2.0 support

### PR DESCRIPTION
**Pull request by pedrogxv**
All the main things I did in this PR is contained inside CHANGELOG.md 'Unreleased' section.

## What I've changed?

- Updated dependencies
- Removed unmantained dependencies
- Removed the `processUncoveredFiles` attribute on the `<coverage>` phpunit.xml configuration element. Because it's no longer supported.

## Notes

1. The main goal of this PR was to update the Pest version used by the package.
2. I could only have a sucessfully test run using Laravel 10... so the new requirement should probably specify this change.
3. I noticed that the supported php versions is kinda odd, I was thinking in including the 8.2... but that's for another PR.

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
@pedrogxv thanks very much for the work here. Are you able to update the GitHub Actions file to remove the outdated checks?

**Comment by pedrogxv** [comment]
Sure, I will take a look.

Em ter., 28 de mar. de 2023 às 10:12, Luke Downing ***@***.***>
escreveu:

**Comment by pedrogxv** [comment]
@lukeraymonddowning just updated the workflow files for accepting the required php versions.

**Comment by pedrogxv** [comment]
The action still fires an error in the `composer update` command, I really could'nt understand it. I was also not able to recreate it locally, it runs normally.

image

 I thought about running `composer update --ignore-platform-reqs` instead, but I dont know if it is a good idea.

**Pull request merged**
